console.log("testando")
var a = 10;
var b = 20;
var total = a+b;
console.log(total)  

var nomePessoa = "Lucas";//var não é obrigatória a declaração/inicialização da variavel
var NOMEPESSOA = "Bernardo";
console.log(nomePessoa)
console.log(NOMEPESSOA)

let _nomeEmpresa = "FAS";
console.log(_nomeEmpresa)

let var1 = 1, 
    var2 = 2,
    var3 = 3;

console.log(var2) //de preferência utilizar let, pois diminui a margem de erro

let book = "Harry Potter"
console.log("book")

book = "Código da vinci"
console.log(book)

const valorConstante = 1000;
console.log("valor constante -->", valorConstante)
